In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [3]:
x + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [6]:
xs = np.array([1, 5, 9])
a = np.arange(1, 4)

print(xs)
print(a)
print(f"xs + a = {xs + a}")

[1 5 9]
[1 2 3]
xs + a = [ 2  7 12]


In [7]:
xs <= a

array([ True, False, False])

# Mehrdimensionale Daten

In [10]:
xs = np.array([
    [1, 6, 4, 2, -1],
    [9, -3, 2, -1, -2],
    [2, 3, -4, 5, 6]
])

print(xs.shape)

(3, 5)


In [14]:
print(xs[1][2])

2


In [15]:
xs[1][2] = 42

In [16]:
print(xs[1][2])

42


In [17]:
xs[:, 2] = np.array([11, 12, 13])

In [18]:
print(xs)

[[ 1  6 11  2 -1]
 [ 9 -3 12 -1 -2]
 [ 2  3 13  5  6]]


# Reshape

In [19]:
xs = np.array([
    [1, 6, 4, 2, -1],
    [9, -3, 2, -1, -2],
    [2, 3, -4, 5, 6]
])

In [20]:
print(xs.reshape(-1))

[ 1  6  4  2 -1  9 -3  2 -1 -2  2  3 -4  5  6]


In [22]:
xs.reshape(5, 3)

array([[ 1,  6,  4],
       [ 2, -1,  9],
       [-3,  2, -1],
       [-2,  2,  3],
       [-4,  5,  6]])

In [25]:
xs.reshape(-1, 5)

array([[ 1,  6,  4,  2, -1],
       [ 9, -3,  2, -1, -2],
       [ 2,  3, -4,  5,  6]])

In [26]:
xs.reshape(-1, 1)

array([[ 1],
       [ 6],
       [ 4],
       [ 2],
       [-1],
       [ 9],
       [-3],
       [ 2],
       [-1],
       [-2],
       [ 2],
       [ 3],
       [-4],
       [ 5],
       [ 6]])

# Operationen

In [28]:
xs = np.array([
    [1, 6, 4, 2, -1],
    [9, -3, 2, -1, -2],
    [2, 3, -4, 5, 6]
])

In [29]:
print(xs.min())
print(xs.max())
print(xs.mean())

-4
9
1.9333333333333333


In [31]:
print(xs.min(axis = 0)) # Min pro Spalte

[ 1 -3 -4 -1 -2]


In [32]:
xs.min(axis=1) # Min pro Zeile

array([-1, -3, -4])

In [34]:
x = np.array([5, 3, 4, 2, 1, 9, 5])

In [37]:
print(x.argmin())
print(x.argmax())

0
5
