In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [2]:
print(a.reshape(-1, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
print(a.reshape(3, 4))  # 3 Datensätze, 4 Features

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
